export interface LessonCard {
  name: string
  grade: string
}

export interface CurriculumSectionData {
  id: string
  label: string
  subtitle: string
  lessons: LessonCard[]
}

export const sharedCurriculumSections: CurriculumSectionData[] = [
  {
    id: 'keyboarding',
    label: 'Keyboarding',
    subtitle: 'Core touch-typing instruction from first key reaches through advanced fluency.',
    lessons: [
      { name: 'Pre-Keyboarding',             grade: 'K–6' },
      { name: 'Learn the Keys',              grade: 'K–12 + Adult' },
      { name: 'Punctuation & Numbers',       grade: '1–3' },
      { name: 'Punctuation & Advanced Keys', grade: '4–12 + Adult' },
      { name: 'Personalized Practice',       grade: 'K–12 + Adult' },
      { name: 'Typing Tests',                grade: 'K–12 + Adult' },
      { name: 'Numeric Keypad / 10-Key',     grade: 'Adult + Core' },
      { name: 'Dvorak Keyboard',             grade: 'Core' },
    ],
  },
  {
    id: 'cross-curricular',
    label: 'Cross-Curricular',
    subtitle: 'Reinforce academic vocabulary and skills across every subject area.',
    lessons: [
      { name: 'Rhyming Words',                grade: 'K–2' },
      { name: 'High Frequency / Sight Words', grade: 'K–2' },
      { name: 'Vocabulary Practice',          grade: 'K–2' },
      { name: 'Context Clues & Root Words',   grade: '3–4' },
      { name: 'Thesaurus Words',              grade: '3–5' },
      { name: 'All About Nouns',              grade: '2–3' },
      { name: 'All About Verbs',              grade: '4' },
      { name: 'Pronouns & Transition Words',  grade: '5–6' },
      { name: 'Parts of a Sentence',          grade: '7' },
      { name: 'Verbals',                      grade: '8' },
      { name: 'Dictionary Definitions',       grade: '6–8' },
      { name: 'Literature',                   grade: '4–8' },
      { name: 'Informational Texts',          grade: '4–12 + Adult' },
      { name: 'Paragraph Practice',           grade: '5–12 + Adult' },
      { name: 'Script Writing',               grade: '9–12 + Adult' },
      { name: 'MLA Citations',               grade: '9–12 + Core' },
      { name: 'Test-Prep Vocabulary',         grade: '9–12' },
      { name: 'Collecting Data',              grade: '5–8' },
      { name: 'Pattern Puzzles',              grade: '3–4, 6' },
      { name: 'Concept Maps',                 grade: '5–8' },
      { name: 'Curious Creations',            grade: '1–5' },
    ],
  },
  {
    id: 'digital-citizenship',
    label: 'Digital Citizenship',
    subtitle: 'Navigate the digital world safely and responsibly.',
    lessons: [
      { name: 'Using Devices & Resources',      grade: 'K–2' },
      { name: 'Commenting with Kindness',        grade: 'K–2' },
      { name: 'Surfing Safety',                  grade: 'K–4' },
      { name: 'Password Privacy',                grade: 'K–5' },
      { name: 'Internet Search Tips',            grade: '1–9 + Core' },
      { name: 'Online Behavior',                 grade: '4–5' },
      { name: 'Cyber Safety',                    grade: '5–8' },
      { name: 'Digital Ethics',                  grade: '3–8' },
      { name: 'Media Literacy',                  grade: '7–12 + Adult' },
      { name: 'Ethics, Values, & Privacy',       grade: '9–12 + Adult' },
      { name: 'Email Rules & Manners',           grade: '3–9 + Core' },
      { name: 'Email Practice Activities',       grade: '5–9' },
      { name: 'Using Technology Responsibly',    grade: '5–8' },
      { name: 'Exploring Emerging Technology',   grade: '1–8' },
      { name: 'Tech Detectives',                 grade: '3–8' },
      { name: 'Resume Practice',                 grade: '10–12 + Adult' },
    ],
  },
  {
    id: 'ai-literacy',
    label: 'AI Literacy',
    subtitle: 'Build foundational knowledge and critical thinking skills around artificial intelligence.',
    lessons: [
      { name: 'What is AI?',                          grade: '3–5' },
      { name: 'Using AI Responsibly & Safely',        grade: '3–5' },
      { name: 'AI and Creativity',                    grade: '3–5' },
      { name: 'Essential AI Vocabulary',              grade: '6–8' },
      { name: 'Understanding AI: Pros and Cons',      grade: '6–8' },
      { name: 'Assessing AI Validity',                grade: '6–8' },
      { name: 'Wildlife Biology Discovery',           grade: '6–8' },
      { name: 'AI in School and the Workplace',       grade: '9–12' },
      { name: 'Evaluating AI Bias',                   grade: '9–12' },
      { name: 'Citing AI Resources',                  grade: '9–12' },
      { name: 'Fantasy Travel Guide',                 grade: '9–12' },
    ],
  },
  {
    id: 'computer-applications',
    label: 'Computer Applications',
    subtitle: 'Practical software skills students and adults use every day.',
    lessons: [
      { name: 'Introduction to Word Processing',   grade: '2–12 + Adult' },
      { name: 'Creating & Saving a Document',      grade: '2–12 + Adult' },
      { name: 'Typing & Selecting Text',           grade: '2–12 + Adult' },
      { name: 'Copying & Pasting Text',            grade: '2–12 + Adult' },
      { name: 'Formatting Font',                   grade: '3–12 + Adult' },
      { name: 'Creating Lists',                    grade: '4–12 + Adult' },
      { name: 'Proofing a Document',               grade: '4–12 + Adult' },
      { name: 'Aligning Text',                     grade: '3–12 + Adult' },
      { name: 'Inserting Images',                  grade: '3–12 + Adult' },
      { name: 'File Management',                   grade: '4–12 + Adult' },
      { name: 'Introduction to Spreadsheets',      grade: '2–12 + Adult' },
      { name: 'Creating & Saving a Spreadsheet',   grade: '2–12 + Adult' },
      { name: 'Entering & Editing Data',           grade: '2–12 + Adult' },
      { name: 'Data Types',                        grade: '5–12 + Adult' },
      { name: 'Using Number Formats',              grade: '3–12 + Adult' },
      { name: 'Sorting Data',                      grade: '4–12 + Adult' },
      { name: 'Creating Charts & Graphs',          grade: '2–12 + Adult' },
      { name: 'Introduction to Presentations',     grade: '3–12 + Adult' },
      { name: 'Creating & Saving a Presentation',  grade: '3–12 + Adult' },
      { name: 'Evaluating Applications',           grade: '4–12' },
    ],
  },
  {
    id: 'coding',
    label: 'Coding',
    subtitle: 'Introductory and intermediate programming concepts for every level.',
    lessons: [
      { name: 'Exploring Patterns',                            grade: 'K–2' },
      { name: 'Discovering Sequences',                         grade: 'K–2' },
      { name: 'The Design Process',                            grade: '1–6' },
      { name: 'Algorithms & Conditionals',                     grade: '2–6' },
      { name: 'The Wonderful World of Variables',              grade: '2–6' },
      { name: 'Introduction to Loops',                         grade: '2–6' },
      { name: 'Mastering the Art of Troubleshooting',          grade: '2–6' },
      { name: 'Using Code to Grow a Beautiful Garden',         grade: '3–5' },
      { name: 'Debugging Real-World Algorithms',               grade: '3–6' },
      { name: 'Battle of the Algorithms',                      grade: '5–6' },
      { name: 'Code Reuse: Coding Concepts in Everyday Life',  grade: '5–6' },
      { name: 'Abstract Thinking: Making Things Simple',       grade: '7–8' },
      { name: 'Understanding Variables',                       grade: '7–8' },
      { name: 'Using Loops: The Power of Iteration',           grade: '7–8' },
      { name: 'Debugging: The Art of Fixing Mistakes',         grade: '7–8' },
      { name: 'Advanced Loops',                                grade: '7–8' },
      { name: 'HTML — The Structure of a Webpage',             grade: '6–12 + Core' },
      { name: 'CSS — Making the Web Beautiful',                grade: '6–12 + Core' },
      { name: 'JavaScript — Programming the Web',              grade: '6–12 + Core' },
    ],
  },
  {
    id: 'creative-writing',
    label: 'Creative Writing',
    subtitle: 'Inspire expression and build writing fluency through meaningful practice.',
    lessons: [
      { name: 'Animals and Nature',                                   grade: '2, 8' },
      { name: 'Family and Friends',                                   grade: '3' },
      { name: 'Sports and Activities',                                grade: '4' },
      { name: 'Travel and Adventure',                                 grade: '5' },
      { name: 'Science and Technology',                               grade: '6' },
      { name: 'Music and Art',                                        grade: '7' },
      { name: 'Persuasive Writing',                                   grade: '2–7' },
      { name: 'Just for Fun',                                         grade: '2–12 + Adult' },
      { name: 'College Application Prep',                             grade: '9–11' },
      { name: 'Job Application Prep',                                 grade: '9–12 + Adult' },
      { name: 'Type Your Own Adventure: Spellbound',                  grade: '4 + Core' },
      { name: 'Type Your Own Adventure: When Robots Rule the World',  grade: '5–6 + Core' },
      { name: 'Type Your Own Adventure: Clandestine',                 grade: '7 + Core' },
      { name: 'Type Your Own Adventure: The Game',                    grade: '8 + Core' },
    ],
  },
  {
    id: 'test-prep',
    label: 'Test Prep',
    subtitle: 'Build the speed and accuracy students need to succeed on digital assessments.',
    lessons: [
      { name: 'Test Prep Vocabulary',          grade: '2–8' },
      { name: 'Reading Comprehension Passages', grade: '2–8' },
      { name: 'Build Your Own Story',           grade: '2–8' },
      { name: 'Short Answer',                   grade: '2–8' },
      { name: 'Essay Questions',                grade: '2–8' },
      { name: 'Timed Response',                 grade: '2–8' },
      { name: 'Test-Prep Vocabulary (SAT/ACT)', grade: '9–12' },
    ],
  },
  {
    id: 'career-prep',
    label: 'Career Prep',
    subtitle: 'Workplace-ready communication and productivity skills for older students and adults.',
    lessons: [
      { name: 'Career Readiness Vocabulary',                                grade: 'Adult' },
      { name: 'Alpha Data Entry',                                            grade: 'Adult + Core' },
      { name: 'Alphanumeric Data Entry',                                     grade: 'Adult + Core' },
      { name: 'Resume Practice',                                             grade: '10–12 + Adult' },
      { name: 'Career Prep',                                                 grade: 'Adult + Core' },
      { name: 'Time Management',                                             grade: 'Adult + Core' },
      { name: 'Communication & Collaboration',                               grade: 'Core' },
      { name: 'Basic Professional Writing',                                  grade: 'Core' },
      { name: 'Block Style Letter / Business Envelope / Personal Business Letter', grade: 'Core' },
      { name: 'Email Correspondence',                                        grade: 'Core' },
      { name: 'Formal Report',                                               grade: 'Core' },
      { name: 'Presentations',                                               grade: 'Core' },
      { name: 'Editing & Proofreading',                                      grade: 'Core' },
      { name: 'Evaluating Software',                                         grade: 'Core' },
      { name: 'Computer Hardware & Maintenance',                             grade: 'Core' },
    ],
  },
  {
    id: 'standards',
    label: 'Standards',
    subtitle: 'Dedicated state curricula custom-built for Texas and New York. State-specific alignments for 11 additional states, plus ISTE and Common Core nationwide.',
    lessons: [
      { name: 'Texas (Proclamation 2024)', grade: 'K–6 TEKS' },
      { name: 'New York',                  grade: 'State Standards' },
      { name: 'Arizona',                   grade: 'State Alignment' },
      { name: 'Alaska',                    grade: 'State Alignment' },
      { name: 'Florida',                   grade: 'State Alignment' },
      { name: 'Idaho',                     grade: 'State Alignment' },
      { name: 'Indiana',                   grade: 'State Alignment' },
      { name: 'Minnesota',                 grade: 'State Alignment' },
      { name: 'Nebraska',                  grade: 'State Alignment' },
      { name: 'New Jersey',                grade: 'State Alignment' },
      { name: 'Oklahoma',                  grade: 'State Alignment' },
      { name: 'South Carolina',            grade: 'State Alignment' },
      { name: 'Virginia',                  grade: 'State Alignment' },
      { name: 'ISTE Standards',            grade: 'National' },
      { name: 'Common Core (CCSS)',        grade: 'National' },
      { name: 'All 50 States',             grade: 'Coverage' },
    ],
  },
  {
    id: 'custom-lessons',
    label: 'Custom Lessons',
    subtitle: 'Your content, your way — build lessons that match exactly what your students need.',
    lessons: [
      { name: 'Standard Typing Screens',        grade: '' },
      { name: 'Advanced Typing Screens',        grade: '' },
      { name: 'Game Screens',                   grade: '' },
      { name: 'Falling Letter Screens',         grade: '' },
      { name: 'Block Letter Screens',           grade: '' },
      { name: 'Coding Screens',                 grade: '' },
      { name: 'Timed Typing Tests (30s–10 min)', grade: '' },
      { name: 'Written Prompts & Free Response', grade: '' },
      { name: 'Drag-and-Drop Screen Reordering', grade: '' },
      { name: 'Assign to Classes & Track Progress', grade: '' },
      { name: 'Multi-Screen Lessons',           grade: '' },
    ],
  },
]
